name: CI

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100'
    - name: Build
      run: dotnet build -c Release
    - uses: actions/upload-artifact@v1
      with:
        name: EFBulkInsert.nupkg
        path: EFBulkInsert\bin\Release\EFBulkInsert.*.nupkg
