name: Pack & publish

on: [push]

jobs:
  pack-publish:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100'
    - name: Pack nuget
      run: dotnet pack -c Release
    - name: Publish
      run: |
        dotnet nuget push "EFBulkInsert\bin\Release\EFBulkInsert.0.4.0.nupkg" --source "github"
        dotnet nuget push "EFBulkInsertCore\bin\Release\EFBulkInsert.0.4.0.nupkg" --source "github"
